from __future__ import annotations

import os
from pathlib import Path

from fastapi import FastAPI, Header, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

try:
    # Running as package: python -m uvicorn backend.main:app
    from .agents.crawler.deterministic import load_posts, process_posts
    from .cron_pipeline import run_safewatch_pipeline
except ImportError:
    # Running from backend/: python -m uvicorn main:app
    from agents.crawler.deterministic import load_posts, process_posts
    from cron_pipeline import run_safewatch_pipeline

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_INPUT_PATH = PROJECT_ROOT / "data" / "sample_posts.json"

app = FastAPI(
    title="PettyCrimeSingapore API",
    description="API for serving incident drafts generated by the crawler agent.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


def read_incident_drafts(input_path: Path = DEFAULT_INPUT_PATH) -> list[dict]:
    if not input_path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Input file not found: {input_path}",
        )

    try:
        posts = load_posts(input_path)
        return process_posts(posts)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


def verify_cron_authorization(authorization: str | None) -> None:
    cron_secret = os.getenv("CRON_SECRET")
    if not cron_secret:
        raise HTTPException(status_code=500, detail="CRON_SECRET is not configured.")

    if authorization != f"Bearer {cron_secret}":
        raise HTTPException(status_code=401, detail="Unauthorized")


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/api/incidents")
def list_incidents(
    candidate_only: bool = Query(default=False, description="Return only candidate incidents."),
    limit: int = Query(default=50, ge=1, le=500, description="Maximum incidents returned."),
) -> dict[str, object]:
    incidents = read_incident_drafts()

    if candidate_only:
        incidents = [incident for incident in incidents if incident.get("candidate") is True]

    incidents = incidents[:limit]

    return {
        "count": len(incidents),
        "incidents": incidents,
    }


@app.get("/api/cron/safewatch")
def run_safewatch_cron(
    authorization: str | None = Header(default=None),
) -> dict[str, object]:
    verify_cron_authorization(authorization)

    try:
        return run_safewatch_pipeline()
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Cron pipeline failed: {exc}") from exc


@app.get("/")
def root() -> dict[str, str]:
    return {
        "message": "PettyCrimeSingapore API is running.",
        "docs": "/docs",
    }
