from __future__ import annotations

"""
feedback.py — Database operations for the 'agent_feedback' table.

This table stores the messages that agents send to each other as part of the
feedback loop described in Section 8 of the project spec. When one agent cannot
complete its task (e.g. the location is too vague), it sends a structured feedback
message to another agent asking for help.

HOW THE FEEDBACK LOOP WORKS:
    1. Crawler Agent processes a post and saves an incident draft.
    2. Classifier Agent tries to classify it but finds the location is unclear.
    3. Classifier Agent calls insert_feedback() to ask the Crawler for more info.
    4. Crawler Agent calls get_unresolved_feedback(to_agent="crawler") to check
       its task queue, finds the request, fetches more data, and updates the incident.
    5. Crawler Agent calls mark_feedback_resolved() to close the loop.
    6. Classifier Agent re-evaluates the incident with the new information.

THREE FEEDBACK CHANNELS (from the project spec):
    Classifier → Crawler        e.g. "location unclear, find more details"
    Decision Agent → Classifier e.g. "re-evaluate ambiguous category scores"
    Decision Agent → Crawler    e.g. "source metadata missing"

TABLE SCHEMA (defined in agents_feedback.sql):
    id               uuid    — Unique ID, auto-generated by Supabase
    incident_id      uuid    — Which incident this feedback is about (foreign key)
    from_agent       text    — Who sent the feedback: "crawler", "classifier", "decision_agent"
    to_agent         text    — Who should act on it: "crawler", "classifier", "decision_agent"
    feedback_type    text    — Short code for the type of issue:
                               "location_unclear", "time_missing", "source_weak",
                               "text_too_vague", "possible_duplicate",
                               "authenticity_too_low", "category_conflict",
                               "severity_unclear", "source_metadata_missing"
    reason           text    — Human-readable explanation of why the feedback was sent
    requested_action text    — Specific instruction for what the receiving agent should do
    priority         text    — Urgency: "low", "medium", or "high"
    resolved         boolean — Has this been acted on? Default: false
    created_at       timestamptz — When the feedback was sent (auto-set by Supabase)
"""

from .supabase import get_supabase_client

# The name of the table in our Supabase database
FEEDBACK_TABLE = "agent_feedback"

_AGENT_ROLE_ALIASES = {
    "crawler": "crawler",
    "cleaner": "cleaner",
    "classifier": "classifier",
    "decision": "decision_agent",
    "decider": "decision_agent",
    "decision_agent": "decision_agent",
}

_PRIORITY_ALIASES = {
    "low": "low",
    "medium": "normal",
    "normal": "normal",
    "high": "high",
    "urgent": "urgent",
}


def _normalise_agent_role(value: object) -> str:
    role = str(value or "").strip().lower().replace(" ", "_")
    if role in _AGENT_ROLE_ALIASES:
        return _AGENT_ROLE_ALIASES[role]
    raise ValueError(f"Invalid agent role for agent_feedback: {value!r}")


def _normalise_priority(value: object) -> str:
    priority = str(value or "normal").strip().lower()
    if priority in _PRIORITY_ALIASES:
        return _PRIORITY_ALIASES[priority]
    raise ValueError(f"Invalid agent_feedback.priority: {value!r}")


# -----------------------------------------------------------------------
# CREATE — Send a new feedback message between agents
# -----------------------------------------------------------------------

def insert_feedback(feedback_data: dict) -> dict:
    """
    Save a new agent-to-agent feedback message to the database.

    This is called whenever one agent needs to communicate a problem or
    request to another agent. The receiving agent will poll for its pending
    messages using get_unresolved_feedback().

    Args:
        feedback_data (dict): The feedback message to save. Must include:
            incident_id (str)      — UUID of the related incident
            from_agent (str)       — Who is sending: "classifier" or "decision_agent"
            to_agent (str)         — Who should receive: "crawler" or "classifier"
            feedback_type (str)    — Short code for the issue type
            reason (str)           — Why is this feedback being sent?
            requested_action (str) — What should the receiving agent do?
            priority (str)         — "low", "medium", or "high"

    Returns:
        dict: The newly created feedback record, including the auto-generated 'id'
              and 'created_at' fields.

    Raises:
        Exception: If the database insert fails.

    Example (from project spec, Section 8):
        # Classifier Agent finds the location is unclear
        feedback = insert_feedback({
            "incident_id": "550e8400-e29b-41d4-a716-446655440000",
            "from_agent": "classifier",
            "to_agent": "crawler",
            "feedback_type": "location_unclear",
            "reason": "The post mentions 'near the station' but does not specify which station.",
            "requested_action": "Search title, comments, and metadata for stronger location evidence.",
            "priority": "medium"
        })
        print(f"Feedback sent with ID: {feedback['id']}")
    """
    client = get_supabase_client()
    payload = dict(feedback_data)
    payload["from_agent"] = _normalise_agent_role(payload.get("from_agent"))
    payload["to_agent"] = _normalise_agent_role(payload.get("to_agent"))
    payload["priority"] = _normalise_priority(payload.get("priority"))

    response = (
        client
        .table(FEEDBACK_TABLE)
        .insert(payload)
        .execute()
    )

    return response.data[0]


# -----------------------------------------------------------------------
# READ — Retrieve feedback messages
# -----------------------------------------------------------------------

def get_feedback_for_incident(incident_id: str) -> list[dict]:
    """
    Retrieve the complete feedback history for a specific incident.

    This gives you the full conversation thread between agents for a given
    incident — useful for understanding why an incident went through multiple
    revision cycles, and for displaying the agent reasoning in the dashboard.

    Args:
        incident_id (str): The UUID of the incident to look up feedback for.

    Returns:
        list[dict]: All feedback records for that incident, ordered from
                    oldest to newest (so you can follow the conversation).
                    Returns an empty list [] if no feedback exists.

    Example:
        messages = get_feedback_for_incident("550e8400-...")

        for message in messages:
            status = "✓ resolved" if message["resolved"] else "⏳ pending"
            print(f"[{status}] {message['from_agent']} → {message['to_agent']}: {message['reason']}")
    """
    client = get_supabase_client()

    response = (
        client
        .table(FEEDBACK_TABLE)
        .select("*")
        .eq("incident_id", incident_id)     # Only this incident's feedback
        .order("created_at", desc=False)    # Oldest first — follow the conversation thread
        .execute()
    )

    return response.data


def get_unresolved_feedback(to_agent: str | None = None) -> list[dict]:
    """
    Retrieve all feedback messages that have not yet been marked as resolved.

    Agents call this to check their "inbox" — a list of tasks they have been
    asked to complete by other agents.

    Args:
        to_agent (str | None): If provided, only return feedback directed at this agent.
                               Valid values: "crawler", "classifier", "decision_agent"
                               If None, return ALL unresolved feedback for all agents.

    Returns:
        list[dict]: Unresolved feedback records, ordered oldest-first.
                    Returns an empty list [] if there are no pending tasks.

    Example:
        # Crawler Agent checks its task queue at the start of each cycle
        crawler_tasks = get_unresolved_feedback(to_agent="crawler")

        if not crawler_tasks:
            print("Crawler: No pending feedback — nothing to do.")
        else:
            for task in crawler_tasks:
                print(f"Task [{task['priority']}]: {task['requested_action']}")
    """
    client = get_supabase_client()

    # Start building the query — we always filter for unresolved messages
    query = (
        client
        .table(FEEDBACK_TABLE)
        .select("*")
        .eq("resolved", False)      # WHERE resolved = false
    )

    # If a specific agent was requested, add that filter too
    if to_agent is not None:
        query = query.eq("to_agent", _normalise_agent_role(to_agent))

    # Oldest first so agents process tasks in the order they were received
    response = query.order("created_at", desc=False).execute()

    return response.data


def get_all_feedback(limit: int = 100) -> list[dict]:
    """
    Retrieve all feedback records, both resolved and unresolved.

    Useful for auditing the full agent communication history or for
    displaying the feedback log in an admin dashboard.

    Args:
        limit (int): Maximum number of records to return. Defaults to 100.

    Returns:
        list[dict]: All feedback records, newest first.
    """
    client = get_supabase_client()

    response = (
        client
        .table(FEEDBACK_TABLE)
        .select("*")
        .order("created_at", desc=True)     # Newest feedback first
        .limit(limit)
        .execute()
    )

    return response.data


# -----------------------------------------------------------------------
# UPDATE — Mark feedback as handled
# -----------------------------------------------------------------------

def mark_feedback_resolved(feedback_id: str) -> dict:
    """
    Mark a feedback message as resolved after the receiving agent has acted on it.

    This closes the feedback loop. Once resolved, the feedback record remains
    in the database for auditing, but it will no longer appear in
    get_unresolved_feedback() results.

    Args:
        feedback_id (str): The UUID of the feedback record to resolve.
                           This is the 'id' field (NOT incident_id) of the feedback record.

    Returns:
        dict: The updated feedback record with resolved=True.

    Raises:
        Exception: If the update fails or the feedback_id doesn't exist.

    Example:
        # Crawler Agent found the location information and resolved the feedback
        resolved = mark_feedback_resolved("feedback-uuid-here")
        print(f"Feedback resolved at: {resolved['created_at']}")
    """
    client = get_supabase_client()

    response = (
        client
        .table(FEEDBACK_TABLE)
        .update({"resolved": True})     # Set resolved = true
        .eq("id", feedback_id)          # For THIS specific feedback record (not incident_id)
        .execute()
    )

    return response.data[0]


def resolve_all_feedback_for_incident(incident_id: str) -> list[dict]:
    """
    Mark ALL unresolved feedback for a specific incident as resolved.

    This is useful when an incident moves to a final state (published, rejected)
    and we want to close all open feedback loops at once.

    Args:
        incident_id (str): The UUID of the incident whose feedback should be resolved.

    Returns:
        list[dict]: The updated feedback records.
    """
    client = get_supabase_client()

    response = (
        client
        .table(FEEDBACK_TABLE)
        .update({"resolved": True})
        .eq("incident_id", incident_id)     # For this incident
        .eq("resolved", False)              # Only update the ones that are still open
        .execute()
    )

    return response.data
