from __future__ import annotations

"""
incidents.py — Database operations for the 'incidents' table.

Every function in this file does exactly ONE thing with the incidents table.
Keeping functions small and focused makes the code easier to understand,
test, and reuse across different parts of the application.

HOW THIS FITS INTO THE SYSTEM:
    Crawler Agent  → calls insert_incident()           to save a new draft
    Classifier Agent → calls update_incident()         to add category/scores
    Decision Agent → calls update_incident_status()    to set final decision
    FastAPI (main.py) → calls get_all_incidents()      to serve the frontend
    Frontend map   → reads published incidents via the API

TABLE SCHEMA (defined in incidents.sql):
    incident_id       uuid    — Unique ID, auto-generated by Supabase
    source_platform   text    — Where the post came from (e.g. "reddit")
    source_url        text    — URL to the original post
    raw_text          text    — The original unmodified post text
    category          text    — Crime type: theft, vandalism, harassment,
                                attempted_theft, suspicious_activity
    authenticity_score float  — How likely the report is real (0.0 = fake, 1.0 = certain)
    severity          float   — How serious the incident is (0.0 = minor, 1.0 = severe)
    location_text     text    — Human-readable location (e.g. "Bedok MRT")
    latitude          float   — GPS latitude coordinate
    longitude         float   — GPS longitude coordinate
    timestamp_text    text    — Raw time mention from post (e.g. "last night", "yesterday")
    normalized_time   timestamptz — Parsed timestamp in UTC
    candidate_scores  jsonb   — Per-category keyword match scores (dictionary)
    matched_signals   jsonb   — List of matched rule keywords
    status            text    — Current workflow state (see STATUS VALUES below)
    duplicate_of      uuid    — If a duplicate, the ID of the original incident
    decision          text    — Final decision from Decision Agent
    agent_notes       jsonb   — List of notes left by each agent as they process the incident
    created_at        timestamptz — Auto-set by Supabase when record is created
    updated_at        timestamptz — Should be updated whenever the record changes

STATUS VALUES (from the project spec):
    "raw"            — Just ingested by the Crawler, not yet processed
    "candidate"      — Crawler flagged this as a possible real incident
    "classified"     — Classifier Agent has scored it
    "published"      — Decision Agent approved it; appears on the public map
    "rejected"       — Decision Agent rejected it (too vague, duplicate, etc.)
    "merged"         — Combined into an existing incident (it was a duplicate)
    "needs_revision" — Sent back to an earlier agent for more information
"""

from .supabase import get_supabase_client

# -----------------------------------------------------------------------
# CONSTANT — The name of the Supabase table we are working with.
# Using a constant means if the table is ever renamed, we only change it here.
# -----------------------------------------------------------------------
INCIDENTS_TABLE = "incidents"


# -----------------------------------------------------------------------
# CREATE — Save a new incident
# -----------------------------------------------------------------------

def insert_incident(incident_data: dict) -> dict:
    """
    Save a new incident record to the database.

    Called by the Crawler Agent after it processes a community post and
    determines it might be a real incident worth investigating further.

    The 'incident_data' dictionary should contain the fields listed in the
    table schema above. You do NOT need to include:
        - incident_id  (Supabase auto-generates a UUID)
        - created_at   (Supabase sets this automatically)
        - updated_at   (Supabase sets this automatically)

    Args:
        incident_data (dict): The incident fields to save. At minimum, include:
            - source_platform (str): e.g. "reddit"
            - source_url (str): URL to the original post
            - raw_text (str): The original post text
            - status (str): Starting status, usually "raw" or "candidate"

    Returns:
        dict: The newly created incident record, including the auto-generated
              incident_id, created_at, and updated_at fields.

    Raises:
        Exception: If the database insert fails (e.g. network error, constraint violation).

    Example:
        new_incident = insert_incident({
            "source_platform": "reddit",
            "source_url": "https://reddit.com/r/singapore/comments/abc123",
            "raw_text": "Someone stole my bicycle at Bedok MRT last night!",
            "status": "raw"
        })
        print(f"Saved with ID: {new_incident['incident_id']}")
    """
    # Get the shared, cached Supabase client
    client = get_supabase_client()

    # Build and execute the INSERT query.
    # .execute() sends the request to Supabase and returns a response object.
    response = (
        client
        .table(INCIDENTS_TABLE)
        .insert(incident_data)
        .execute()
    )

    # response.data is a list of inserted records.
    # We inserted one record, so we return the first (and only) item.
    return response.data[0]


# -----------------------------------------------------------------------
# READ — Retrieve incidents from the database
# -----------------------------------------------------------------------

def get_incident_by_id(incident_id: str) -> dict | None:
    """
    Retrieve a single incident using its unique ID.

    Args:
        incident_id (str): The UUID of the incident. This is the value in the
                           'incident_id' column (auto-generated when inserted).

    Returns:
        dict: The incident record if found.
        None: If no incident with that ID exists in the database.

    Example:
        incident = get_incident_by_id("550e8400-e29b-41d4-a716-446655440000")

        if incident is None:
            print("No incident found with that ID.")
        else:
            print(f"Found: {incident['category']} at {incident['location_text']}")
    """
    client = get_supabase_client()

    response = (
        client
        .table(INCIDENTS_TABLE)
        .select("*")                        # * means "all columns"
        .eq("incident_id", incident_id)     # WHERE incident_id = <the given value>
        .execute()
    )

    # .data is a list; if empty, the incident wasn't found
    if response.data:
        return response.data[0]

    return None


def get_all_incidents(
    status_filter: str | None = None,
    limit: int = 50
) -> list[dict]:
    """
    Retrieve a list of incidents, optionally filtered by status.

    This is the main function used by the API to get incidents for the
    frontend dashboard.

    Args:
        status_filter (str | None): If given, only return incidents with this status.
                                    Pass None to get incidents of ALL statuses.
                                    Valid values: "raw", "candidate", "classified",
                                    "published", "rejected", "merged", "needs_revision"
        limit (int): Maximum number of incidents to return. Defaults to 50.
                     Use a higher number (e.g. 500) to get everything.

    Returns:
        list[dict]: A list of incident records. Each item is a dictionary with
                    all the column values. Returns an empty list [] if none found.

    Example:
        # Get the 20 most recently published incidents
        published = get_all_incidents(status_filter="published", limit=20)

        # Get ALL incidents regardless of status (up to 100)
        everything = get_all_incidents(limit=100)
    """
    client = get_supabase_client()

    # Start building the query — we will add filters before executing
    query = client.table(INCIDENTS_TABLE).select("*")

    # Add the status filter only if one was provided
    if status_filter is not None:
        # .eq() adds: WHERE status = <status_filter>
        query = query.eq("status", status_filter)

    # Sort by created_at descending (newest incidents appear first)
    # then apply the row limit
    query = query.order("created_at", desc=True).limit(limit)

    # Send the query to Supabase and get the results
    response = query.execute()

    # response.data is already a list of dictionaries — return it directly
    return response.data


def get_published_incidents(limit: int = 100) -> list[dict]:
    """
    Retrieve all incidents that have been approved and published to the public map.

    This is a convenience function — it just calls get_all_incidents() with
    status_filter="published" so callers don't have to remember the string.

    Args:
        limit (int): Maximum number of published incidents to return.

    Returns:
        list[dict]: A list of published incident records.

    Example:
        map_pins = get_published_incidents()
        for pin in map_pins:
            print(f"{pin['category']} at ({pin['latitude']}, {pin['longitude']})")
    """
    return get_all_incidents(status_filter="published", limit=limit)


def get_candidate_incidents(limit: int = 100) -> list[dict]:
    """
    Retrieve all incidents that the Crawler has flagged as candidates
    but that have not yet been processed by the Classifier Agent.

    These are incidents waiting in the queue to be classified.

    Args:
        limit (int): Maximum number of candidates to return.

    Returns:
        list[dict]: A list of candidate incident records.
    """
    return get_all_incidents(status_filter="candidate", limit=limit)


# -----------------------------------------------------------------------
# UPDATE — Modify existing incidents
# -----------------------------------------------------------------------

def update_incident(incident_id: str, updates: dict) -> dict:
    """
    Update one or more fields of an existing incident.

    You only need to include the fields you want to change in the 'updates'
    dictionary — you do NOT need to send the full incident object.

    This function is called by:
        - Classifier Agent: to add category, scores, and severity
        - Decision Agent: to set the final decision and change the status

    Args:
        incident_id (str): The UUID of the incident to update.
        updates (dict): A dictionary of fields to change. Only include the
                        fields that should be updated. Everything else stays the same.

    Returns:
        dict: The updated incident record (all fields, not just the changed ones).

    Raises:
        Exception: If the update fails or the incident_id does not exist.

    Example:
        # Classifier Agent saves its findings
        updated = update_incident("550e8400-...", {
            "category": "theft",
            "authenticity_score": 0.82,
            "severity": 0.65,
            "location_text": "Bedok MRT",
            "latitude": 1.3240,
            "longitude": 103.9300,
            "status": "classified"
        })
    """
    client = get_supabase_client()

    response = (
        client
        .table(INCIDENTS_TABLE)
        .update(updates)                    # The fields to change
        .eq("incident_id", incident_id)     # Only update THIS specific incident
        .execute()
    )

    return response.data[0]


def update_incident_status(incident_id: str, new_status: str) -> dict:
    """
    Change just the status field of an incident.

    A simplified wrapper around update_incident() for when you only need to
    change the status. This is commonly called by the Decision Agent.

    Valid status values:
        "raw"            — Just ingested, not yet processed
        "candidate"      — Crawler approved it as a possible real incident
        "classified"     — Classifier Agent has scored it
        "published"      — Approved; visible on the public map
        "rejected"       — Rejected; not shown on the map
        "merged"         — Merged into another incident (it was a duplicate)
        "needs_revision" — Sent back to an earlier agent for more information

    Args:
        incident_id (str): The UUID of the incident to update.
        new_status (str): The new status value.

    Returns:
        dict: The updated incident record.

    Example:
        # Decision Agent approves the incident
        update_incident_status("550e8400-...", "published")

        # Decision Agent rejects the incident
        update_incident_status("550e8400-...", "rejected")
    """
    return update_incident(incident_id, {"status": new_status})


def append_agent_note(
    incident_id: str,
    note: str,
    existing_notes: list[str]
) -> dict:
    """
    Add a new note to an incident's agent_notes list.

    The 'agent_notes' column is a JSONB array in the database. To add a note,
    we take the existing list, append the new note, and save the whole list back.

    We need 'existing_notes' as a parameter because Supabase (PostgreSQL) does not
    support a simple "append to array" operation via the Python SDK — we have to
    fetch the current notes first, then save the updated list.

    Args:
        incident_id (str): The UUID of the incident to update.
        note (str): The new note text to add. Convention is to include the agent name,
                    e.g. "Classifier Agent: assigned category=theft, score=0.82"
        existing_notes (list[str]): The current list of notes from the incident record.
                                    Pass an empty list [] if there are no existing notes.

    Returns:
        dict: The updated incident record.

    Example:
        # First fetch the incident to get its current notes
        incident = get_incident_by_id("550e8400-...")
        current_notes = incident.get("agent_notes") or []

        # Then add your new note
        updated = append_agent_note(
            incident_id="550e8400-...",
            note="Decision Agent: published after passing authenticity threshold.",
            existing_notes=current_notes
        )
    """
    # Create a new list with the new note added at the end.
    # We use list(existing_notes) to make a copy, so we don't accidentally
    # modify the original list that was passed in.
    updated_notes = list(existing_notes) + [note]

    return update_incident(incident_id, {"agent_notes": updated_notes})
