from __future__ import annotations

"""
mock_reports.py — Database operations for the 'mock_official_reports' table.

PURPOSE:
    In the real world, we would check against official Singapore Police Force (SPF)
    reports, CNA news articles, or Straits Times to see if a community-reported
    incident has already been officially documented. Since we cannot access live
    official APIs in this MVP, we use a pre-populated database table as a stand-in.

HOW IT IS USED IN THE WORKFLOW:
    The Classifier Agent calls find_similar_official_report() before scoring an
    incident. If a match is found, the incident is marked as "already_reported"
    so we do not re-publish something the authorities already know about.

    From the project spec (Section 2 — Excluded posts):
        "Incidents already covered by official or mainstream sources"

    The logic (from Section 11 — MVP Scope):
        if similar incident exists in mock official reports:
            mark as already_reported
        else:
            mark as potentially_unreported

IMPORTANT LIMITATION:
    The current find_similar_official_report() uses simple text matching.
    A more robust version would use vector embeddings (pgvector) to find
    semantically similar reports even when the wording differs. The
    'category_prototypes' table is set up for this future upgrade.

TABLE SCHEMA (defined in mock_official_reports.sql):
    id               uuid        — Unique ID, auto-generated by Supabase
    title            text        — Short headline of the official report
    description      text        — Full description of the incident
    category         text        — Crime type (matches our incident categories)
    location_text    text        — Human-readable location (e.g. "Bedok MRT")
    latitude         float       — GPS latitude coordinate
    longitude        float       — GPS longitude coordinate
    reported_at      timestamptz — When this was officially reported
    source           text        — Where it came from: "SPF", "CNA", "Straits Times", etc.
"""

from .supabase import get_supabase_client

# The name of the table in our Supabase database
MOCK_REPORTS_TABLE = "mock_official_reports"


# -----------------------------------------------------------------------
# READ — Retrieve mock official reports
# -----------------------------------------------------------------------

def get_all_mock_reports() -> list[dict]:
    """
    Retrieve all mock official reports from the database.

    Returns:
        list[dict]: All official report records, sorted newest-first.
                    Returns an empty list [] if the table is empty.

    Example:
        all_reports = get_all_mock_reports()
        print(f"Database contains {len(all_reports)} official reports.")

        for report in all_reports:
            print(f"[{report['source']}] {report['title']} — {report['location_text']}")
    """
    client = get_supabase_client()

    response = (
        client
        .table(MOCK_REPORTS_TABLE)
        .select("*")
        .order("reported_at", desc=True)    # Most recently reported first
        .execute()
    )

    return response.data


def find_similar_official_report(
    category: str,
    location_text: str
) -> dict | None:
    """
    Search for an official report that matches the given category and location.

    This is the key function used by the Classifier Agent to check whether a
    community post is describing something already officially reported.

    HOW THE MATCHING WORKS:
        We do a two-part filter:
        1. category must EXACTLY match (e.g. both must be "theft")
        2. location_text must PARTIALLY match using case-insensitive search
           (e.g. searching "Bedok" will match "Bedok MRT" and "Near Bedok Station")

    LIMITATION:
        This is a simple string-based match and will miss cases where the same
        location is described differently (e.g. "Bedok" vs "East Coast"). A future
        version using vector embeddings (pgvector) would handle these cases better.

    Args:
        category (str): The crime category to look for. Must match the categories
                        used in our incidents table:
                        "theft", "attempted_theft", "vandalism",
                        "suspicious_activity", "harassment"
        location_text (str): A location string to search for. Can be partial —
                             e.g. "Bedok" will match "Bedok MRT" in the database.

    Returns:
        dict: The first matching official report found, if any.
        None: If no matching official report exists.

    Example:
        # Check if a theft at Bedok MRT is already officially reported
        existing = find_similar_official_report(
            category="theft",
            location_text="Bedok MRT"
        )

        if existing is not None:
            print(f"Already reported by {existing['source']} on {existing['reported_at']}")
            # → Mark the community incident as "already_reported"
        else:
            print("Not in official records — this could be an unreported incident!")
            # → Mark the community incident as "potentially_unreported"
    """
    client = get_supabase_client()

    response = (
        client
        .table(MOCK_REPORTS_TABLE)
        .select("*")
        # Filter 1: exact match on category
        .eq("category", category)
        # Filter 2: case-insensitive partial match on location_text
        # ilike = case-insensitive LIKE, the % symbols are wildcards
        # so "%Bedok MRT%" matches anything containing "bedok mrt" (case-insensitive)
        .ilike("location_text", f"%{location_text}%")
        # We only need the first match to know a similar report exists
        .limit(1)
        .execute()
    )

    # Return the matching report if found, or None if the table had no match
    if response.data:
        return response.data[0]

    return None


def get_reports_by_category(category: str) -> list[dict]:
    """
    Get all official reports for a specific crime category.

    Useful for getting context about how many official reports exist for a
    given crime type, which can inform severity scoring.

    Args:
        category (str): The crime category to filter by.

    Returns:
        list[dict]: All official reports with that category.

    Example:
        theft_reports = get_reports_by_category("theft")
        print(f"There are {len(theft_reports)} officially reported theft cases in the database.")
    """
    client = get_supabase_client()

    response = (
        client
        .table(MOCK_REPORTS_TABLE)
        .select("*")
        .eq("category", category)
        .order("reported_at", desc=True)
        .execute()
    )

    return response.data


# -----------------------------------------------------------------------
# CREATE — Seed the database with mock data
# -----------------------------------------------------------------------

def insert_mock_report(report_data: dict) -> dict:
    """
    Add a new mock official report to the database.

    This is used for seeding the database with test data before a demo.
    In a real production system, official reports would come from external APIs.

    Args:
        report_data (dict): The report to add. Should include:
            title (str)          — Short headline, e.g. "Bicycle theft at Bedok MRT"
            description (str)    — Full description of the incident
            category (str)       — Crime category
            location_text (str)  — Human-readable location
            latitude (float)     — GPS latitude
            longitude (float)    — GPS longitude
            reported_at (str)    — ISO 8601 timestamp, e.g. "2026-04-20T10:00:00+08:00"
            source (str)         — "SPF", "CNA", "Straits Times", etc.

    Returns:
        dict: The newly created report record, including the auto-generated 'id'.

    Example:
        new_report = insert_mock_report({
            "title": "Bicycle theft at Bedok MRT",
            "description": "A bicycle was reported stolen from the Bedok MRT bicycle rack on the morning of April 20.",
            "category": "theft",
            "location_text": "Bedok MRT",
            "latitude": 1.3240,
            "longitude": 103.9300,
            "reported_at": "2026-04-20T10:00:00+08:00",
            "source": "SPF"
        })
        print(f"Saved official report with ID: {new_report['id']}")
    """
    client = get_supabase_client()

    response = (
        client
        .table(MOCK_REPORTS_TABLE)
        .insert(report_data)
        .execute()
    )

    return response.data[0]


def seed_mock_reports(reports: list[dict]) -> list[dict]:
    """
    Insert multiple mock official reports at once (bulk insert).

    Use this to populate the database with a batch of test data before running a demo.

    Args:
        reports (list[dict]): A list of report dictionaries. Each should have the
                              same fields as described in insert_mock_report().

    Returns:
        list[dict]: The newly created report records.

    Example:
        from backend.db.mock_reports import seed_mock_reports

        seed_mock_reports([
            {
                "title": "Theft at Tampines Mall",
                "description": "Wallet reported stolen from unattended bag.",
                "category": "theft",
                "location_text": "Tampines Mall",
                "latitude": 1.3530,
                "longitude": 103.9450,
                "reported_at": "2026-04-15T14:00:00+08:00",
                "source": "CNA"
            },
            {
                "title": "Vandalism at Ang Mo Kio MRT",
                "description": "Graffiti found on station walls.",
                "category": "vandalism",
                "location_text": "Ang Mo Kio MRT",
                "latitude": 1.3699,
                "longitude": 103.8495,
                "reported_at": "2026-04-10T08:30:00+08:00",
                "source": "Straits Times"
            },
        ])
    """
    client = get_supabase_client()

    response = (
        client
        .table(MOCK_REPORTS_TABLE)
        .insert(reports)    # Supabase accepts a list for bulk insert
        .execute()
    )

    return response.data
